Consider the below code to answer further questions:

In [9]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [10]:
list_

['1', '2', '3', '4', '5']

In [11]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

yes, there is a difference in the data type of variable list_ and array_list . The list_ variable is a python list while array_list variable is NumPy array.

In [18]:
type(list_)

list

In [19]:
type(array_list)

numpy.ndarray

Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [25]:
for item in list_:
    print(type(item))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [27]:
for item1 in array_list:
    print(type(item1))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


Q3. Considering the following changes in the variable, array_list:

In [38]:
arra_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [39]:
list_

['1', '2', '3', '4', '5']

In [40]:
arra_list

array([1, 2, 3, 4, 5])

yes there is defference in data type of elements present in both variables , list_ and arra_list when arra_list variable with dtypes=int the elements will be converted into integers while the element in the list_  variable will be remains string. 

In [41]:
for item in list_:
    print(type(item))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [42]:
for item in arra_list:
    print(type(item))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


Consider the below code to answer further questions:

In [43]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

Q4. Write a code to find the following characteristics of variable, num_array:

(i) shape
(ii) size

In [46]:
num_array.shape

(2, 3)

In [47]:
num_array.size

6

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

In [48]:
data=np.random.randint(0,1,(3,3))

In [49]:
np.matrix(data)

matrix([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [53]:
data1=np.diag([1,1,1,1,1,])

In [54]:
np.matrix(data1)

matrix([[1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1]])

In [55]:
data1.shape

(5, 5)